package at.ac.uibk.dps.cirrina.observability.tracing;

public enum MethodName {
  DO_ENTER,
  DO_EXIT,
  ON_RECEIVE_EVENT,
  TRY_SELECT_ON_TRANSITION,
  TRY_SELECT_ALWAYS_TRANSITION,
  TRY_SELECT_TRANSITION,
  HANDLE_EVENT,
  EXECUTE,
  START_ALL_TIMEOUT_ACTIONS,
  STOP_ALL_TIMEOUT_ACTIONS,
  STOP_TIMEOUT_ACTION,
  SWITCH_ACTIVE_STATE,
  DO_TRANSITION,
  HANDLE_INTERNAL_TRANSITION,
  HANDLE_EXTERNAL_TRANSITION,
  HANDLE_TRANSITION,
  EXECUTE_ACTION,
  CREATE_ACTION_COMMAND,
  EVALUATE,
  SEND_EVENT,
  START,
  STOP,
  STOP_ALL,
  INVOKE,
  SELECT
}
