name: Build
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  Build:
    if: github.repository == 'CollaborativeStateMachines/Cirrina'
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Perform commit linting
        uses: wagoid/commitlint-github-action@v6

      - name: Install Protocol Buffers compiler
        uses: arduino/setup-protoc@v3

      - name: Build using Gradle
        run: ./gradlew build

      - name: Test using Gradle
        run: ./gradlew test