name: Build and Publish CSM Package
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  release:
    types: [ published ]
jobs:
  build-csm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build CSM Docker image
        run: docker build -t csm-builder -f Dockerfile.pkl .

      - name: Create container
        run: docker create --name csm-container csm-builder

      - name: Copy Pkl package out
        run: docker cp csm-container:/usr/src/csm/out ./out

      - name: Upload development artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: CSM
          path: ./out

      - name: Upload Pkl package to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: ./out/**