name: Publish Artifacts
on:
  release:
    types: [ published ]
jobs:
  Publish:
    name: Publish Artifacts to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Build
        run: ./gradlew build

      - name: Build distribution ZIP
        run: ./gradlew distZip

      - name: Upload release artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/distributions/*.zip
            ATTRIBUTIONS.md
            LICENSE
          token: ${{ secrets.GITHUB_TOKEN }}

